### ISSUE TITLE
Pushing Hubot commits to `master`

### ISSUE THREAD

**Issue by mikemcquaid** [github/developer.github.com#986]
Hello watchers of developer.github.com! I've briefly enabled Issues on this repository to solicit your opinions.

As you may have noticed our bot, @hubot, creates pull requests and automatically merges them (e.g. https://github.com/github/developer.github.com/pull/985). We're consider moving these to having @hubot commit directly to the `master` branch which would mean there's less noise from pull requests being open/closed by the bot and the only pull requests would be from humans.

Does anyone have a preference as to whether we maintain the current behaviour (@hubot opens PRs) or move to the alternative behaviour (@hubot commits directly to `master`)?

Thanks!

**Comment by davidcelis** [comment]
I'd personally like to see the PR noise go down. I don't have a problem with @hubot committing directly to master, but I'm willing to defer to others on that bit and listen for potential problems there.

**Comment by Shredder121** [comment]
My 2 cents:

I regularly check the health of the repository, and go to the pull request overview for that.
(I should probably watch this repository, but am only interested in one subdirectory).

All in all, I think that PRs are much better, since when watching you are notified of such activity.

Thoughts?

**Comment by gjtorikian** [comment]
> I regularly check the health of the repository

Could you elaborate? We're never not going to update our API documentation!

**Comment by Shredder121** [comment]
There are specific directories (`lib/webhooks`, `lib/responses`) that I check for changes.
It's pretty hard to be aware of changes when there are no pull requests.

**Comment by gjtorikian** [comment]
It sounds like we should definitely do a better job communicating if our payload responses change. But beyond that I am not sure there is an advantage in keeping the automated pull requests going, since one would need to check each and every one to see which files changed.

**Comment by Shredder121** [comment]
@gjtorikian *Yes* that would be good when consuming them! :+1: 

This sounds 'sort of' in line with what is requested in [Missing payload schemas descriptions](https://github.com/github/developer.github.com/issues/996).

If there is a better way to communicate changes (maybe also blog posts about that) then I'm fine with less noise in this repo. :wink:

**Comment by mikemcquaid** [comment]
We're going to move towards pushing things directly to `master` due to a lack of community/watcher outcry on this. Thanks for your input @Shredder121; we'll bear that in mind and try to improve in this area going forward.
