### ISSUE TITLE
add possibility to vote on issues

### ISSUE THREAD

**Issue by vrms** [github/developer.github.com#994]
This is kind of a feature request to github and t be honest I am not 100% sure whether this is the right place for it. If not maybe someone with more insight can kindly point in the right direction.

what I wanted to request is adding the possibility to vote on issues. This kind of results from [this issue](https://github.com/frappe/erpnext/issues/4063) 

At present any github user can comment on any issue and try to raise awareness to it to the developers (given the fact that user can not just fix an issue he/she wants to be fixed) like this. This practice for sure can give a hint to any team but the ability to vote would make preferences/needs of a community much clearer and therefore help to steer a project in the right direction

**Comment by Shredder121** [comment]
This repository is just for the developer.github.com website.
If there is anything you'd like to see in the platform itself, then support@github.com is the place to go.

Just my 2 cents, I've been using ZenHub, which does have voting support.
It would however be very neat to have voting support as first class citizen, maybe even with webhook for a `vote` event.

**Comment by gjtorikian** [comment]
Yes, this is just for the developer website.
