### ISSUE TITLE
Apache license not correct detected

### ISSUE THREAD

**Issue by Horcrux7** [github/developer.github.com#998]
The license API does not correct detect the Apache License 2.0 if the license file contains only a snippet. If there is a full copy then it work. My understanding of the Apache License is that the snippet ist the correct license file: http://www.apache.org/licenses/LICENSE-2.0#apply

Working:
https://api.github.com/repos/less/less.js/license

Not working:
https://api.github.com/repos/i-net-software/SetupBuilder/license

**Comment by mikemcquaid** [comment]
Hi @Horcrux7! We don't accept issues for github.com in this repository. Can you instead report this issue to our support team? Thanks!
